name: Run vite build
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v2
      - name: Install frontend dependencies
        run: npm install
      - name: Build frontend
        run: npm run build
